package org.grajagan.envoy.om;


/**
 * Maps ResultSet rows into Equipment objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Oct 25 14:51:38 PDT 2013]
 *
 */
public class EquipmentRecordMapper extends BaseEquipmentRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1382737898078L;



}
