package org.grajagan.envoy.om;


/**
 * The reports stored
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Oct 25 14:51:36 PDT 2013]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class Report
    extends org.grajagan.envoy.om.BaseReport
{
    /** Serial version */
    private static final long serialVersionUID = 1382737896203L;



}
