package org.grajagan.om;


/**
 * Maps ResultSet rows into Envoy objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Oct 25 14:51:38 PDT 2013]
 *
 */
public class EnvoyRecordMapper extends BaseEnvoyRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1382737898075L;



}
