package org.grajagan.om;


/**
 * Maps ResultSet rows into Interval objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Oct 25 14:51:38 PDT 2013]
 *
 */
public class IntervalRecordMapper extends BaseIntervalRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1382737898079L;



}
