package org.grajagan.om;


/**
 * Maps ResultSet rows into Reading objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Oct 25 14:51:38 PDT 2013]
 *
 */
public class ReadingRecordMapper extends BaseReadingRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1382737898081L;



}
