package org.grajagan.om;

/**
 * The reports stored
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Oct 25 14:51:37 PDT 2013]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class ReportPeer
    extends org.grajagan.om.BaseReportPeer
{

}
